### ISSUE TITLE
Invalid Zig install path

### ISSUE THREAD

**Issue by yay** [ice1000/zig-intellij#30] opened 2019-04-25 19:18 UTC
What is `install path`?

Is it `/usr/local/Cellar/zig/0.4.0/`? (I've installed Zig via Homebrew), or some arbitrary folder to install binaries to? It feels like I've tried everything at this point, but it still doesn't work.

I just see this all the time:
<img width="179" alt="Screen Shot 2019-04-25 at 20 17 49" src="https://user-images.githubusercontent.com/1799756/56762206-3cd7a980-6797-11e9-843e-9f0285c7d965.png">

**Comment by ice1000** [comment] 2019-04-25 19:20
I'm gonna fix it soon. The installation path validator is based on Zig 0.3.0 preview, which is deprecated.
Sorry for the inconvenience

**Comment by yay** [comment] 2019-04-25 19:24
OK, thanks, looking forward to trying your plugin!

**Comment by ice1000** [comment] 2019-04-25 19:37
Closing as being duplicate of #29.

**Closed as completed by ice1000** 2019-04-25 19:37 UTC
Labels: duplicate

**Comment by ice1000** [comment] 2019-04-26 21:17
Since #29 is closed, I'll release 0.1.2 which may fix this issue.
